# -*- mode: python ; coding: utf-8 -*-
# ============================================================================
# packaging/mirrorz.spec - PyInstaller build recipe for MirrorZ-Hecras
# ============================================================================
# PyInstaller freezes the Python interpreter + our code + dependencies into
# a self-contained app the user can run WITHOUT installing Python. This one
# spec file drives all three platforms; the build scripts in this folder
# invoke it with:    pyinstaller packaging/mirrorz.spec
#
# HIGHLIGHTED TWEAK AREAS
#   ### TWEAK: APP_IDENTITY ###  name / bundle id / version live here
#   ### TWEAK: EXCLUDES ###      modules stripped to shrink the bundle
# ============================================================================

import os
import sys

# Resolve the repo root whether pyinstaller is run from the root or from
# packaging/. SPECPATH is provided by PyInstaller (dir containing this file).
ROOT = os.path.abspath(os.path.join(SPECPATH, os.pardir))
sys.path.insert(0, ROOT)

from mirrorz import __version__, APP_NAME   # single source of truth

# ### TWEAK: APP_IDENTITY ###
BUNDLE_ID = "com.mirrorz.hecras"    # reverse-DNS id; must match your Apple
                                    # Developer App ID for store submission.

# Platform-appropriate icon (generated by packaging/make_icons.py).
if sys.platform == "darwin":
    ICON = os.path.join(ROOT, "assets", "mirrorz.icns")
elif os.name == "nt":
    ICON = os.path.join(ROOT, "assets", "mirrorz.ico")
else:
    ICON = os.path.join(ROOT, "assets", "mirrorz_256.png")
if not os.path.exists(ICON):
    ICON = None     # icons are optional for a dev build

a = Analysis(
    [os.path.join(ROOT, "main.py")],
    pathex=[ROOT],
    binaries=[],
    # Bundle the example projects + docs so File->Open has something to show.
    datas=[
        (os.path.join(ROOT, "examples"), "examples"),
        (os.path.join(ROOT, "docs", "tutorial.md"), "docs"),
    ],
    # tkinter backends sometimes need a nudge to be discovered.
    hiddenimports=[
        "matplotlib.backends.backend_tkagg",
        "matplotlib.backends.backend_agg",   # report.py HTML thumbnails
        "matplotlib.backends.backend_pdf",   # report.py PDF assembly
        "PIL._tkinter_finder",
    ],
    # ### TWEAK: EXCLUDES ### - strip heavyweight things we never import.
    # Each exclusion shaves megabytes off the installer. If a future feature
    # starts importing one of these, REMOVE it from this list.
    #
    # scipy is the big one: ~73 MB bundled, and we only use one function
    # (scipy.optimize.brentq) for root-finding. mirrorz/hydraulics.py ships
    # a pure-Python bisection fallback that produces identical answers
    # within tolerance. The frozen build uses the fallback; source installs
    # that have scipy still use brentq for the small speed win.
    excludes=[
        "scipy",                # ~73 MB - use bisection fallback instead
        "pytest", "setuptools", "pip",
        "IPython", "jupyter", "notebook",
        "PyQt5", "PyQt6", "PySide2", "PySide6",  # we use Tk, not Qt
        "sphinx", "babel", "lib2to3",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP_NAME,
    debug=False,
    strip=False,
    upx=False,            # UPX-compressed binaries trip Gatekeeper/AV scans
    console=False,        # windowed app: no terminal window pops up
    icon=ICON,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name=APP_NAME,
)

# macOS: wrap the collected folder into a real .app bundle with the metadata
# Gatekeeper, notarization, and the App Store all read from Info.plist.
if sys.platform == "darwin":
    app = BUNDLE(
        coll,
        name=f"{APP_NAME}.app",
        icon=ICON,
        bundle_identifier=BUNDLE_ID,
        version=__version__,
        info_plist={
            "CFBundleShortVersionString": __version__,
            "CFBundleVersion": __version__,
            "NSHighResolutionCapable": True,
            "LSMinimumSystemVersion": "11.0",
            "NSHumanReadableCopyright":
                "© 2026 MirrorZ-Hecras contributors. MIT License.",
            # App Sandbox category shown in the Mac App Store.
            "LSApplicationCategoryType": "public.app-category.education",
        },
    )
